Error checks in startup script
git-svn-id: https://svn.mcs.anl.gov/repos/exm/sfw/turbine/trunk@3119 dc4e9af1-7f46-4ead-bba6-71afc04862de

diff --git a/code/bin/turbine b/code/bin/turbine
--- a/code/bin/turbine
+++ b/code/bin/turbine
@@ -34,6 +34,17 @@ PROGRAM=$1
 shift
 ARGS=${*}
 
+if [[ ${PROGRAM} == "" ]]
+then
+  echo "turbine: no program!"
+  exit 1
+fi
+if [[ ! -f ${PROGRAM} ]]
+then
+  echo "turbine: program not found: ${PROGRAM}"
+  exit 1
+fi
+
 OPTS=
 OPTS+="${L} "
 OPTS+="-n ${PROCS} "
