Better startup error checks
git-svn-id: https://svn.mcs.anl.gov/repos/exm/sfw/turbine/trunk@3221 dc4e9af1-7f46-4ead-bba6-71afc04862de

diff --git a/code/bin/turbine b/code/bin/turbine
--- a/code/bin/turbine
+++ b/code/bin/turbine
@@ -57,6 +57,11 @@ then
 fi
 
 source ${TURBINE_HOME}/scripts/turbine-config.sh
+if [[ ${?} != 0 ]]
+then
+  echo "turbine: configuration error!"
+  exit 1
+fi
 
 # Allow user to insert valgrind
 ${TURBINE_LAUNCH} ${OPTS} ${VALGRIND} ${TCLSH} ${PROGRAM} ${ARGS}
